packages:
  - apps/*
  - packages/*

catalog:
  '@trpc/client': ^11.5.0
  '@trpc/server': ^11.6.0
  better-auth: ^1.3.27
  dotenv: ^17.2.3
  drizzle-orm: ^0.44.2
  tsdown: ^0.15.6
  typescript: ^5.9.3
  zod: ^4.1.12
