packages:
  - apps/*
  - packages/*
catalog:
  "@trpc/server": ^11.5.0
  better-auth: ^1.3.13
  dotenv: ^17.2.2
  zod: ^4.1.11
  typescript: ^5.8.2
  tsdown: ^0.15.5
  "@trpc/client": ^11.5.0
  drizzle-orm: ^0.44.2
